# ansible/provision.yml

---
- name: Provision ML Docker API Server
  hosts: all
  become: yes

  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy application files
      copy:
        src: ../
        dest: /opt/ml-docker-orchestrator
        mode: 0755

    - name: Build and run container
      shell: |
        cd /opt/ml-docker-orchestrator
        docker build -t ml-docker-api -f docker/Dockerfile .
        docker run -d -p 8000:8000 ml-docker-api
